# Generated by Django 5.2.4 on 2025-08-03 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.service'),
        ),
    ]
