# Generated by Django 5.2.4 on 2025-08-03 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_booking_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='service_type',
            new_name='service',
        ),
    ]
