# Generated by Django 5.2.4 on 2025-08-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_customer_name_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
