# Generated by Django 5.2.4 on 2025-08-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_booking_user_booking_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
